### ISSUE TITLE
Connect to remote IP?

### ISSUE THREAD

**Issue by rsewell97** [deblockt/google-home-push#1]
Hi, 

Was wondering if there is a way to broadcast a message to a remote IP for a smart home application or if this is intentionally blocked? 

I get the obvious 'not found' error:
![image](https://user-images.githubusercontent.com/38791439/50717995-8767d580-1083-11e9-8a1e-ab643fa84d4f.png)

Thanks for any help or pointers in advance!

**Comment by rsewell97** [comment]
Was a simple fix in the end. For anyone trying to replicate this, I modified __init__.py to become:
![image](https://user-images.githubusercontent.com/38791439/50730752-936b9a00-114c-11e9-9ffc-272bd2f4529e.png)

Perhaps consider merging this feature for a future release?

**Comment by deblockt** [comment]
I will take account of your code.
