### ISSUE TITLE
Issue running script

### ISSUE THREAD

**Issue by peterd550** [deblockt/google-home-push#5]
When I use the example and change to my device name in Google home

from googlehomepush import GoogleHome

GoogleHome("Google-Nest").say("test")
GoogleHome("Google-Nest").play("http://www.hubharp.com/web_sound/BachGavotteShort.mp3")

When I run the python script in vscode I get the following error.

Failed to connect, retrying in 5.0s

Any help would be appreciated

**Comment by peterd550** [comment]
Found how it is mean to work. Doco is not clear.
You can not ping the hostname ofyou device 
you need to make it static in your router and use this what I did


text = 'Hello how are you?'
GoogleHome(host = "THE IP OF DEVICE").say(text, lang='en-GB')
GoogleHome(host = "THE IP OF DEVICE").play("http://www.hubharp.com/web_sound/BachGavotteShort.mp3")

Now it works

**Comment by viditagrawal** [comment]
hey, sorry not sure I understood your fix to this problem.

I'm having the same issue, where do I find this IP of the google home mini?

**Comment by peterd550** [comment]
Use an ip scanner 
Then in your router you set them to static 
That way the IP address doesn't change
